### ISSUE TITLE
Duplicate "ghost" interfaces

### ISSUE THREAD

**Issue by tomm2000** [AE2-UEL/Applied-Energistics-2#399] opened 2024-02-12 15:03 UTC
**Describe the bug**

The network reports the existance of "ghost" interfaces on the network, these are duplicates of other interfaces. Even after removing the original interface the "ghost" is still present (and still shows in the interface terminal list). I've notice this happen mostly with interfaces inside compact machines.

**To Reproduce**

from what i gathered this is when it happens, tho im not sure if it happens all the time:
- create a compact machine (https://www.curseforge.com/minecraft/mc-mods/compact-machines)

- connect an interface inside the machine using ME capability adapters (https://www.curseforge.com/minecraft/mc-mods/capability-adapter)
- put a crafting pattern inside the interface

**Expected behavior**

There should not be duplicates of the interface

**Additional context**

The interface is duplicated, both the ghost and real interface show up in the terminal and both are in the same location:
![1](https://github.com/AE2-UEL/Applied-Energistics-2/assets/38072918/4d9211b1-baac-4069-88c5-630f832e16fb)
![2024-02-12_11 41 28](https://github.com/AE2-UEL/Applied-Energistics-2/assets/38072918/821d642c-fef7-4a25-ae8b-55a0346c3aff)

After removing the real interface the "ghost" is still there, it still shows in the terminal and with the highlight:
![2](https://github.com/AE2-UEL/Applied-Energistics-2/assets/38072918/6d279058-db38-4a89-ba7c-c5416fd93924)
![2024-02-12_11 42 28](https://github.com/AE2-UEL/Applied-Energistics-2/assets/38072918/9594424a-ab8d-487b-8363-7e19febc4a24)

**Environment**

The modpack is https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended version 1.29.1
The modpack is hosted on a server

- Minecraft Version: 1.12
- AE2 Version: ae2-uel-v0.56.2
- Forge Version: 14.23.5.2860

**Comment by PunishedBadger** [comment] 2024-02-14 11:47
Having this same problem, let me know if you find a fix

**Comment by zeng-github01** [comment] 2024-02-17 08:29
Have you tried using quantum bridge internally? If this is the case, the display is normal. It's just an adapter problem @tomm2000 @PunishedBadger

**Comment by PunishedBadger** [comment] 2024-02-17 17:33
Tested with quantum bridge and it worked fine on server restart. Suspect you're right and it's a capability adapter issue. Found a similar issue from a while ago https://github.com/ruifung/MECapabilityAdapter/issues/13

**Comment by zeng-github01** [comment] 2024-02-18 10:06
> Tested with quantum bridge and it worked fine on server restart. Suspect you're right and it's a capability adapter issue. Found a similar issue from a while ago [ruifung/MECapabilityAdapter#13](https://github.com/ruifung/MECapabilityAdapter/issues/13)

I recently realized that the Part variant of this adapter cannot connect to the ME network. So I guessed this question
glad to help you

**Comment by PunishedBadger** [comment] 2024-02-21 17:31
It appears that something was broken when the mod was rewritten for 1.1. Reverting to 1.0 fixes the problem.

**Comment by NotMyWing** [comment] 2024-05-09 06:44
Since this is confirmed to be more of a capability adapter mod issue, I'm closing this for now.

**Closed by NotMyWing** 2024-05-09 06:44 UTC
