### ISSUE TITLE
Crash when try to craft something in Arcane Crafting Terminal

### ISSUE THREAD

**Issue by mczph** [AE2-UEL/Applied-Energistics-2#400] opened 2024-02-13 05:32 UTC
https://mclo.gs/HHisMtD

AE2UEL:0.56.3
[Thaumic Energistics Extended Life](https://www.curseforge.com/minecraft/mc-mods/thaumic-energistics-extended-life):2.2.7

**Comment by zeng-github01** [comment] 2024-05-17 09:22
duplicate of #418

**Closed** 2024-05-17 13:43 UTC
