### ISSUE TITLE
[Crash] unknow reason cause crash

### ISSUE THREAD

**Issue by zeng-github01** [AE2-UEL/Applied-Energistics-2#463] opened 2024-06-16 12:41 UTC
**Describe the bug**
Random crashes on the server

**To Reproduce**
Just play Minecraft for a while

**Expected behavior**

Not Crash

**Additional context**

**Environment**
[crash-2024-06-15_17.44.42-server.txt](https://github.com/user-attachments/files/15858007/crash-2024-06-15_17.44.42-server.txt)

- Minecraft Version: 
- AE2 Version: 0.56,5
- Forge Version: Latest

**Comment by NotMyWing** [comment] 2024-06-18 08:34
Could you please describe what your Export Buses are trying to auto-craft? From what I'm seeing, the relevant code parts shouldn't ever change the item list during iteration, at least under normal circumstances... unless something from a different thread is fiddling with the storage? maybe?

**Comment by zeng-github01** [comment] 2024-06-18 11:45
I only have a few buses with crafting cards. They are made of various stones.

Connected to Nuclear Craft's Stone Crusher. Used to automate using redstone signals. Because the output of this machine is probabilistic

There are three types of stones, as follows

![Screenshot_2024-06-18-19-44-37-87_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/AE2-UEL/Applied-Energistics-2/assets/95841646/9a90b200-a116-4703-b16a-4587bec587a8)

**Comment by zeng-github01** [comment] 2024-06-18 11:47
In the game that crashed, I did not trigger the automatic crafting in these buses. So I don't know what caused it.

**Comment by NotMyWing** [comment] 2024-06-21 02:43
Very oddly, the crash log says otherwise. I'll close this for now since it feels like a complete fluke, at least until the reproduction steps or exact cause are figured out.

**Closed by NotMyWing** 2024-06-21 02:43 UTC
Labels: bug, question
