### ISSUE TITLE
ME interface not exporting items in v0.56.6

### ISSUE THREAD

**Issue by royalmustard** [AE2-UEL/Applied-Energistics-2#456] opened 2024-06-12 16:08 UTC
**Describe the bug**
After updating from rv6-stable-7-extended_life-v0.55.27 to v0.56.6, item interfaces no longer export any items. 
![image](https://github.com/AE2-UEL/Applied-Energistics-2/assets/36129876/7f6074ec-149c-439d-a781-b98d08e63679)

My theory is that it is actually exporting the item but then immediately importing it again into the ME system. 
I come to this conclusion because when setting up two storage locations with different priorities, an interface exporting an item will not have it stay exported but rather move the items from the low to the high priority storage.

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version:  v0.56.6
- Forge Version: 14.23.5.2860

**Comment by zeng-github01** [comment] 2024-06-13 09:03
Possibly caused by #448  @NotMyWing

**Comment by NotMyWing** [comment] 2024-06-13 09:31
Fixed in #454.

**Closed by NotMyWing** 2024-06-13 09:31 UTC
